services:
- type: web
  name: StockMate47
  runtime: python
  repo: https://github.com/juanphiri7/StockMate
  plan: free
  region: oregon
  envVars:
        - key: DATABASE_PATH
          value: /app/database.db
        - key: FLASK_SECRET_KEY
          python -c "import secrets; print(secrets.token_hex(16))"
        - key: ADMIN_PASSWORD
          value: StockMateAdmin@47
  buildCommand: pip install -r requirements.txt
  startCommand: python app.py
  autoDeployTrigger: commit
version: "1"
